name: lausanne-heat-islands
channels:
  - conda-forge
dependencies:
  - pip
  - make
  - notebook
  - setuptools
  - wheel
  - click
  - sphinx
  - coverage
  - flake8
  - awscli  
  - python-dotenv>=0.5.1
  - python=3.7
  - ipykernel
  - boto3
  - tqdm
  - numpy<1.17  # because of laspy
  - gdal<3.0
  - geopandas<0.7  # because of salem
  - rasterio
  - xlrd
  - xarray
  - netcdf4
  - scikit-learn=0.22.1  # better algorithm default args
  - descartes
  - contextily
  - seaborn
  - statsmodels
  - s3fs  
  - fsspec
  - dask
